// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCalendarServiceDeleteEventParams creates a new CalendarServiceDeleteEventParams object
// with the default values initialized.
func NewCalendarServiceDeleteEventParams() *CalendarServiceDeleteEventParams {
	var ()
	return &CalendarServiceDeleteEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCalendarServiceDeleteEventParamsWithTimeout creates a new CalendarServiceDeleteEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCalendarServiceDeleteEventParamsWithTimeout(timeout time.Duration) *CalendarServiceDeleteEventParams {
	var ()
	return &CalendarServiceDeleteEventParams{

		timeout: timeout,
	}
}

// NewCalendarServiceDeleteEventParamsWithContext creates a new CalendarServiceDeleteEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewCalendarServiceDeleteEventParamsWithContext(ctx context.Context) *CalendarServiceDeleteEventParams {
	var ()
	return &CalendarServiceDeleteEventParams{

		Context: ctx,
	}
}

// NewCalendarServiceDeleteEventParamsWithHTTPClient creates a new CalendarServiceDeleteEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCalendarServiceDeleteEventParamsWithHTTPClient(client *http.Client) *CalendarServiceDeleteEventParams {
	var ()
	return &CalendarServiceDeleteEventParams{
		HTTPClient: client,
	}
}

/*CalendarServiceDeleteEventParams contains all the parameters to send to the API endpoint
for the calendar service delete event operation typically these are written to a http.Request
*/
type CalendarServiceDeleteEventParams struct {

	/*EventID*/
	EventID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) WithTimeout(timeout time.Duration) *CalendarServiceDeleteEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) WithContext(ctx context.Context) *CalendarServiceDeleteEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) WithHTTPClient(client *http.Client) *CalendarServiceDeleteEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) WithEventID(eventID int32) *CalendarServiceDeleteEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the calendar service delete event params
func (o *CalendarServiceDeleteEventParams) SetEventID(eventID int32) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *CalendarServiceDeleteEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param event_id
	if err := r.SetPathParam("event_id", swag.FormatInt32(o.EventID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
