// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vitamin-nn/otus_hometask/hw12_13_14_15_calendar/tests/httpclient/models"
)

// NewCalendarServiceGetEventsDayParams creates a new CalendarServiceGetEventsDayParams object
// with the default values initialized.
func NewCalendarServiceGetEventsDayParams() *CalendarServiceGetEventsDayParams {
	var ()
	return &CalendarServiceGetEventsDayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCalendarServiceGetEventsDayParamsWithTimeout creates a new CalendarServiceGetEventsDayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCalendarServiceGetEventsDayParamsWithTimeout(timeout time.Duration) *CalendarServiceGetEventsDayParams {
	var ()
	return &CalendarServiceGetEventsDayParams{

		timeout: timeout,
	}
}

// NewCalendarServiceGetEventsDayParamsWithContext creates a new CalendarServiceGetEventsDayParams object
// with the default values initialized, and the ability to set a context for a request
func NewCalendarServiceGetEventsDayParamsWithContext(ctx context.Context) *CalendarServiceGetEventsDayParams {
	var ()
	return &CalendarServiceGetEventsDayParams{

		Context: ctx,
	}
}

// NewCalendarServiceGetEventsDayParamsWithHTTPClient creates a new CalendarServiceGetEventsDayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCalendarServiceGetEventsDayParamsWithHTTPClient(client *http.Client) *CalendarServiceGetEventsDayParams {
	var ()
	return &CalendarServiceGetEventsDayParams{
		HTTPClient: client,
	}
}

/*CalendarServiceGetEventsDayParams contains all the parameters to send to the API endpoint
for the calendar service get events day operation typically these are written to a http.Request
*/
type CalendarServiceGetEventsDayParams struct {

	/*Body*/
	Body *models.GetEventsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) WithTimeout(timeout time.Duration) *CalendarServiceGetEventsDayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) WithContext(ctx context.Context) *CalendarServiceGetEventsDayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) WithHTTPClient(client *http.Client) *CalendarServiceGetEventsDayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) WithBody(body *models.GetEventsRequest) *CalendarServiceGetEventsDayParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the calendar service get events day params
func (o *CalendarServiceGetEventsDayParams) SetBody(body *models.GetEventsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CalendarServiceGetEventsDayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
