// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vitamin-nn/otus_hometask/hw12_13_14_15_calendar/tests/httpclient/models"
)

// CalendarServiceGetEventsWeekReader is a Reader for the CalendarServiceGetEventsWeek structure.
type CalendarServiceGetEventsWeekReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CalendarServiceGetEventsWeekReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCalendarServiceGetEventsWeekOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCalendarServiceGetEventsWeekDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCalendarServiceGetEventsWeekOK creates a CalendarServiceGetEventsWeekOK with default headers values
func NewCalendarServiceGetEventsWeekOK() *CalendarServiceGetEventsWeekOK {
	return &CalendarServiceGetEventsWeekOK{}
}

/*CalendarServiceGetEventsWeekOK handles this case with default header values.

A successful response.
*/
type CalendarServiceGetEventsWeekOK struct {
	Payload *models.GetEventsResponse
}

func (o *CalendarServiceGetEventsWeekOK) Error() string {
	return fmt.Sprintf("[POST /get_events_week][%d] calendarServiceGetEventsWeekOK  %+v", 200, o.Payload)
}

func (o *CalendarServiceGetEventsWeekOK) GetPayload() *models.GetEventsResponse {
	return o.Payload
}

func (o *CalendarServiceGetEventsWeekOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetEventsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCalendarServiceGetEventsWeekDefault creates a CalendarServiceGetEventsWeekDefault with default headers values
func NewCalendarServiceGetEventsWeekDefault(code int) *CalendarServiceGetEventsWeekDefault {
	return &CalendarServiceGetEventsWeekDefault{
		_statusCode: code,
	}
}

/*CalendarServiceGetEventsWeekDefault handles this case with default header values.

An unexpected error response
*/
type CalendarServiceGetEventsWeekDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the calendar service get events week default response
func (o *CalendarServiceGetEventsWeekDefault) Code() int {
	return o._statusCode
}

func (o *CalendarServiceGetEventsWeekDefault) Error() string {
	return fmt.Sprintf("[POST /get_events_week][%d] CalendarService_GetEventsWeek default  %+v", o._statusCode, o.Payload)
}

func (o *CalendarServiceGetEventsWeekDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CalendarServiceGetEventsWeekDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
