// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vitamin-nn/otus_hometask/hw12_13_14_15_calendar/tests/httpclient/models"
)

// NewCalendarServiceUpdateEventParams creates a new CalendarServiceUpdateEventParams object
// with the default values initialized.
func NewCalendarServiceUpdateEventParams() *CalendarServiceUpdateEventParams {
	var ()
	return &CalendarServiceUpdateEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCalendarServiceUpdateEventParamsWithTimeout creates a new CalendarServiceUpdateEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCalendarServiceUpdateEventParamsWithTimeout(timeout time.Duration) *CalendarServiceUpdateEventParams {
	var ()
	return &CalendarServiceUpdateEventParams{

		timeout: timeout,
	}
}

// NewCalendarServiceUpdateEventParamsWithContext creates a new CalendarServiceUpdateEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewCalendarServiceUpdateEventParamsWithContext(ctx context.Context) *CalendarServiceUpdateEventParams {
	var ()
	return &CalendarServiceUpdateEventParams{

		Context: ctx,
	}
}

// NewCalendarServiceUpdateEventParamsWithHTTPClient creates a new CalendarServiceUpdateEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCalendarServiceUpdateEventParamsWithHTTPClient(client *http.Client) *CalendarServiceUpdateEventParams {
	var ()
	return &CalendarServiceUpdateEventParams{
		HTTPClient: client,
	}
}

/*CalendarServiceUpdateEventParams contains all the parameters to send to the API endpoint
for the calendar service update event operation typically these are written to a http.Request
*/
type CalendarServiceUpdateEventParams struct {

	/*Body*/
	Body *models.UpdateEventRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) WithTimeout(timeout time.Duration) *CalendarServiceUpdateEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) WithContext(ctx context.Context) *CalendarServiceUpdateEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) WithHTTPClient(client *http.Client) *CalendarServiceUpdateEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) WithBody(body *models.UpdateEventRequest) *CalendarServiceUpdateEventParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the calendar service update event params
func (o *CalendarServiceUpdateEventParams) SetBody(body *models.UpdateEventRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CalendarServiceUpdateEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
