// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vitamin-nn/otus_hometask/hw12_13_14_15_calendar/tests/httpclient/models"
)

// CalendarServiceGetEventsMonthReader is a Reader for the CalendarServiceGetEventsMonth structure.
type CalendarServiceGetEventsMonthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CalendarServiceGetEventsMonthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCalendarServiceGetEventsMonthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCalendarServiceGetEventsMonthDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCalendarServiceGetEventsMonthOK creates a CalendarServiceGetEventsMonthOK with default headers values
func NewCalendarServiceGetEventsMonthOK() *CalendarServiceGetEventsMonthOK {
	return &CalendarServiceGetEventsMonthOK{}
}

/*CalendarServiceGetEventsMonthOK handles this case with default header values.

A successful response.
*/
type CalendarServiceGetEventsMonthOK struct {
	Payload *models.GetEventsResponse
}

func (o *CalendarServiceGetEventsMonthOK) Error() string {
	return fmt.Sprintf("[POST /get_events_month][%d] calendarServiceGetEventsMonthOK  %+v", 200, o.Payload)
}

func (o *CalendarServiceGetEventsMonthOK) GetPayload() *models.GetEventsResponse {
	return o.Payload
}

func (o *CalendarServiceGetEventsMonthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetEventsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCalendarServiceGetEventsMonthDefault creates a CalendarServiceGetEventsMonthDefault with default headers values
func NewCalendarServiceGetEventsMonthDefault(code int) *CalendarServiceGetEventsMonthDefault {
	return &CalendarServiceGetEventsMonthDefault{
		_statusCode: code,
	}
}

/*CalendarServiceGetEventsMonthDefault handles this case with default header values.

An unexpected error response
*/
type CalendarServiceGetEventsMonthDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the calendar service get events month default response
func (o *CalendarServiceGetEventsMonthDefault) Code() int {
	return o._statusCode
}

func (o *CalendarServiceGetEventsMonthDefault) Error() string {
	return fmt.Sprintf("[POST /get_events_month][%d] CalendarService_GetEventsMonth default  %+v", o._statusCode, o.Payload)
}

func (o *CalendarServiceGetEventsMonthDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CalendarServiceGetEventsMonthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
