// Code generated by go-swagger; DO NOT EDIT.

package calendar_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vitamin-nn/otus_hometask/hw12_13_14_15_calendar/tests/httpclient/models"
)

// CalendarServiceCreateEventReader is a Reader for the CalendarServiceCreateEvent structure.
type CalendarServiceCreateEventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CalendarServiceCreateEventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCalendarServiceCreateEventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCalendarServiceCreateEventDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCalendarServiceCreateEventOK creates a CalendarServiceCreateEventOK with default headers values
func NewCalendarServiceCreateEventOK() *CalendarServiceCreateEventOK {
	return &CalendarServiceCreateEventOK{}
}

/*CalendarServiceCreateEventOK handles this case with default header values.

A successful response.
*/
type CalendarServiceCreateEventOK struct {
	Payload *models.ModifyEventResponse
}

func (o *CalendarServiceCreateEventOK) Error() string {
	return fmt.Sprintf("[POST /create][%d] calendarServiceCreateEventOK  %+v", 200, o.Payload)
}

func (o *CalendarServiceCreateEventOK) GetPayload() *models.ModifyEventResponse {
	return o.Payload
}

func (o *CalendarServiceCreateEventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModifyEventResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCalendarServiceCreateEventDefault creates a CalendarServiceCreateEventDefault with default headers values
func NewCalendarServiceCreateEventDefault(code int) *CalendarServiceCreateEventDefault {
	return &CalendarServiceCreateEventDefault{
		_statusCode: code,
	}
}

/*CalendarServiceCreateEventDefault handles this case with default header values.

An unexpected error response
*/
type CalendarServiceCreateEventDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the calendar service create event default response
func (o *CalendarServiceCreateEventDefault) Code() int {
	return o._statusCode
}

func (o *CalendarServiceCreateEventDefault) Error() string {
	return fmt.Sprintf("[POST /create][%d] CalendarService_CreateEvent default  %+v", o._statusCode, o.Payload)
}

func (o *CalendarServiceCreateEventDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CalendarServiceCreateEventDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
