version: "3"

services:
    rabbit:
        container_name: calendar_rabbit
        image: rabbitmq:3.8.7-management-alpine
        env_file:
            - env/rabbit.env
        ports:
            - "5672:5672"
            - "15672:15672"
