// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetEventsRequest get events request
//
// swagger:model GetEventsRequest
type GetEventsRequest struct {

	// begin at
	// Format: date-time
	BeginAt strfmt.DateTime `json:"begin_at,omitempty"`
}

// Validate validates this get events request
func (m *GetEventsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBeginAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetEventsRequest) validateBeginAt(formats strfmt.Registry) error {

	if swag.IsZero(m.BeginAt) { // not required
		return nil
	}

	if err := validate.FormatOf("begin_at", "body", "date-time", m.BeginAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetEventsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetEventsRequest) UnmarshalBinary(b []byte) error {
	var res GetEventsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
